/* -*- C -*- */
/*
 * COPYRIGHT 2016 XYRATEX TECHNOLOGY LIMITED
 *
 * THIS DRAWING/DOCUMENT, ITS SPECIFICATIONS, AND THE DATA CONTAINED
 * HEREIN, ARE THE EXCLUSIVE PROPERTY OF XYRATEX TECHNOLOGY
 * LIMITED, ISSUED IN STRICT CONFIDENCE AND SHALL NOT, WITHOUT
 * THE PRIOR WRITTEN PERMISSION OF XYRATEX TECHNOLOGY LIMITED,
 * BE REPRODUCED, COPIED, OR DISCLOSED TO A THIRD PARTY, OR
 * USED FOR ANY PURPOSE WHATSOEVER, OR STORED IN A RETRIEVAL SYSTEM
 * EXCEPT AS ALLOWED BY THE TERMS OF XYRATEX LICENSES AND AGREEMENTS.
 *
 * YOU SHOULD HAVE RECEIVED A COPY OF XYRATEX'S LICENSE ALONG WITH
 * THIS RELEASE. IF NOT PLEASE CONTACT A XYRATEX REPRESENTATIVE
 * http://www.xyratex.com/contact
 *
 * Original author: Leonid Nikulin <leonid.nikulin@seagate.com>
 * Original creation date: 19-Apr-2016
 */

#pragma once

#ifndef __MERO_CAS_CAS_ADDB2_H__
#define __MERO_CAS_CAS_ADDB2_H__

#include "addb2/identifier.h"  /* M0_AVI_CAS_RANGE_START */
#include "xcode/xcode_attr.h"

/**
 * @defgroup cas-service
 *
 * @{
 */
enum m0_avi_cas_labels {
	M0_AVI_CAS_KV_SIZES = M0_AVI_CAS_RANGE_START + 1,

	M0_AVI_CAS_SM_REQ,
	M0_AVI_CAS_SM_REQ_COUNTER,
	M0_AVI_CAS_SM_REQ_COUNTER_END = M0_AVI_CAS_SM_REQ_COUNTER + 0x100,

	M0_AVI_CAS_TO_RPC,
	M0_AVI_CAS_FOM_TO_CROW_FOM,

	M0_AVI_CAS_REQ_ATTR_IS_META,
	M0_AVI_CAS_REQ_ATTR_REC_NR,

	M0_AVI_CAS_FOM_ATTR_IKV_NR,
	M0_AVI_CAS_FOM_ATTR_IN_INLINE_KEYS_NR,
	M0_AVI_CAS_FOM_ATTR_IN_BULK_KEYS_NR,
	M0_AVI_CAS_FOM_ATTR_IN_KEYS_SIZE,
	M0_AVI_CAS_FOM_ATTR_IN_INLINE_VALS_NR,
	M0_AVI_CAS_FOM_ATTR_IN_BULK_VALS_NR,
	M0_AVI_CAS_FOM_ATTR_IN_VALS_SIZE,

	M0_AVI_CAS_FOM_ATTR_OUT_INLINE_KEYS_NR,
	M0_AVI_CAS_FOM_ATTR_OUT_BULK_KEYS_NR,
	M0_AVI_CAS_FOM_ATTR_OUT_KEYS_SIZE,
	M0_AVI_CAS_FOM_ATTR_OUT_INLINE_VALS_NR,
	M0_AVI_CAS_FOM_ATTR_OUT_BULK_VALS_NR,
	M0_AVI_CAS_FOM_ATTR_OUT_VALS_SIZE,
} M0_XCA_ENUM;


/** @} end of cas-service group */
#endif /* __MERO_CAS_CAS_ADDB2_H__ */

/*
 *  Local variables:
 *  c-indentation-style: "K&R"
 *  c-basic-offset: 8
 *  tab-width: 8
 *  fill-column: 80
 *  scroll-step: 1
 *  End:
 */
/*
 * vim: tabstop=8 shiftwidth=8 noexpandtab textwidth=80 nowrap
 */
