ut_libmero_ut_la_SOURCES += ha/ut/cookie.c \
                            ha/ut/entrypoint.c \
                            ha/ut/ha.c \
                            ha/ut/helper.c \
                            ha/ut/helper.h \
                            ha/ut/link.c \
                            ha/ut/lq.c \
                            ha/ut/main.c \
                            ha/ut/msg_queue.c \
                            ha/ut/note.c
