
/* AUTO-GENERATED!  DO NOT EDIT, CHANGES WILL BE LOST! */

/* generated by server/addb-codegen.py */

/*
 * COPYRIGHT 2019 SEAGATE LLC
 *
 * THIS DRAWING/DOCUMENT, ITS SPECIFICATIONS, AND THE DATA CONTAINED
 * HEREIN, ARE THE EXCLUSIVE PROPERTY OF SEAGATE TECHNOLOGY
 * LIMITED, ISSUED IN STRICT CONFIDENCE AND SHALL NOT, WITHOUT
 * THE PRIOR WRITTEN PERMISSION OF SEAGATE TECHNOLOGY LIMITED,
 * BE REPRODUCED, COPIED, OR DISCLOSED TO A THIRD PARTY, OR
 * USED FOR ANY PURPOSE WHATSOEVER, OR STORED IN A RETRIEVAL SYSTEM
 * EXCEPT AS ALLOWED BY THE TERMS OF SEAGATE LICENSES AND AGREEMENTS.
 *
 * YOU SHOULD HAVE RECEIVED A COPY OF SEAGATE'S LICENSE ALONG WITH
 * THIS RELEASE. IF NOT PLEASE CONTACT A SEAGATE REPRESENTATIVE
 * http://www.seagate.com/contact
 *
 * Original author:  Ivan Tishchenko   <ivan.tishchenko@seagate.com>
 * Original creation date: 28-Oct-2019
 */

#pragma once

#ifndef __S3_SERVER_ADDB_PLUGIN_AUTO_H__
#define __S3_SERVER_ADDB_PLUGIN_AUTO_H__

#include <addb2/addb2_internal.h>

/* See comments in addb-codegen.py and s3_addb.h for more details.
 *
 * This enum defines addb_action_type_id for ADDB logs.  These action types are
 * needed to distinguish different kinds of log entries from each other.
 */
enum S3AddbActionTypeId {

  /* See comment on ext_id_ranges.h above; had to use magic number here,
   * as mero headers are not yet merged to master. */
  S3_ADDB_RANGE_START = M0_ADDB2__EXT_RANGE_1,

  /* helper IDs e.g. for linking requests */

  /* ID of ADDB entry which keeps a mapping of addb_request_id to S3 API-level
   * UUID of the request. */
  S3_ADDB_REQUEST_ID = S3_ADDB_RANGE_START,

  /* ID of ADDB entry which keeps a link between s3 request and clovis op
   * request. */
  S3_ADDB_REQUEST_TO_CLOVIS_ID,

  /* Action classes identifiers: */
  S3_ADDB_FIRST_REQUEST_ID,

  /* S3_ADDB_ACTION_BASE_ID is to be used in constructors, while action class
   * is still being constructed and it is not possible to identify what is the
   * class name of the instance (derived class name). */
  S3_ADDB_ACTION_BASE_ID = S3_ADDB_FIRST_REQUEST_ID,

  /* Auto-generated IDs are listed below. Sorry for strange format, it had to
   * be done this way to pass git-clang-format check. */

  /* MeroDeleteIndexAction: */
  S3_ADDB_MERO_DELETE_INDEX_ACTION_ID,
  /* MeroDeleteKeyValueAction: */
  S3_ADDB_MERO_DELETE_KEY_VALUE_ACTION_ID,
  /* MeroDeleteObjectAction: */
  S3_ADDB_MERO_DELETE_OBJECT_ACTION_ID,
  /* MeroGetKeyValueAction: */
  S3_ADDB_MERO_GET_KEY_VALUE_ACTION_ID,
  /* MeroHeadIndexAction: */
  S3_ADDB_MERO_HEAD_INDEX_ACTION_ID,
  /* MeroHeadObjectAction: */
  S3_ADDB_MERO_HEAD_OBJECT_ACTION_ID,
  /* MeroKVSListingAction: */
  S3_ADDB_MERO_KVS_LISTING_ACTION_ID,
  /* S3AbortMultipartAction: */
  S3_ADDB_S3_ABORT_MULTIPART_ACTION_ID,
  /* S3AccountDeleteMetadataAction: */
  S3_ADDB_S3_ACCOUNT_DELETE_METADATA_ACTION_ID,
  /* S3DeleteBucketAction: */
  S3_ADDB_S3_DELETE_BUCKET_ACTION_ID,
  /* S3DeleteBucketPolicyAction: */
  S3_ADDB_S3_DELETE_BUCKET_POLICY_ACTION_ID,
  /* S3DeleteBucketTaggingAction: */
  S3_ADDB_S3_DELETE_BUCKET_TAGGING_ACTION_ID,
  /* S3DeleteMultipleObjectsAction: */
  S3_ADDB_S3_DELETE_MULTIPLE_OBJECTS_ACTION_ID,
  /* S3DeleteObjectAction: */
  S3_ADDB_S3_DELETE_OBJECT_ACTION_ID,
  /* S3DeleteObjectTaggingAction: */
  S3_ADDB_S3_DELETE_OBJECT_TAGGING_ACTION_ID,
  /* S3GetBucketACLAction: */
  S3_ADDB_S3_GET_BUCKET_ACL_ACTION_ID,
  /* S3GetBucketAction: */
  S3_ADDB_S3_GET_BUCKET_ACTION_ID,
  /* S3GetBucketPolicyAction: */
  S3_ADDB_S3_GET_BUCKET_POLICY_ACTION_ID,
  /* S3GetBucketTaggingAction: */
  S3_ADDB_S3_GET_BUCKET_TAGGING_ACTION_ID,
  /* S3GetBucketlocationAction: */
  S3_ADDB_S3_GET_BUCKETLOCATION_ACTION_ID,
  /* S3GetMultipartBucketAction: */
  S3_ADDB_S3_GET_MULTIPART_BUCKET_ACTION_ID,
  /* S3GetMultipartPartAction: */
  S3_ADDB_S3_GET_MULTIPART_PART_ACTION_ID,
  /* S3GetObjectACLAction: */
  S3_ADDB_S3_GET_OBJECT_ACL_ACTION_ID,
  /* S3GetObjectAction: */
  S3_ADDB_S3_GET_OBJECT_ACTION_ID,
  /* S3GetObjectTaggingAction: */
  S3_ADDB_S3_GET_OBJECT_TAGGING_ACTION_ID,
  /* S3GetServiceAction: */
  S3_ADDB_S3_GET_SERVICE_ACTION_ID,
  /* S3HeadBucketAction: */
  S3_ADDB_S3_HEAD_BUCKET_ACTION_ID,
  /* S3HeadObjectAction: */
  S3_ADDB_S3_HEAD_OBJECT_ACTION_ID,
  /* S3HeadServiceAction: */
  S3_ADDB_S3_HEAD_SERVICE_ACTION_ID,
  /* S3PostCompleteAction: */
  S3_ADDB_S3_POST_COMPLETE_ACTION_ID,
  /* S3PostMultipartObjectAction: */
  S3_ADDB_S3_POST_MULTIPART_OBJECT_ACTION_ID,
  /* S3PutBucketACLAction: */
  S3_ADDB_S3_PUT_BUCKET_ACL_ACTION_ID,
  /* S3PutBucketAction: */
  S3_ADDB_S3_PUT_BUCKET_ACTION_ID,
  /* S3PutBucketPolicyAction: */
  S3_ADDB_S3_PUT_BUCKET_POLICY_ACTION_ID,
  /* S3PutBucketTaggingAction: */
  S3_ADDB_S3_PUT_BUCKET_TAGGING_ACTION_ID,
  /* S3PutChunkUploadObjectAction: */
  S3_ADDB_S3_PUT_CHUNK_UPLOAD_OBJECT_ACTION_ID,
  /* S3PutFiAction: */
  S3_ADDB_S3_PUT_FI_ACTION_ID,
  /* S3PutMultiObjectAction: */
  S3_ADDB_S3_PUT_MULTI_OBJECT_ACTION_ID,
  /* S3PutObjectACLAction: */
  S3_ADDB_S3_PUT_OBJECT_ACL_ACTION_ID,
  /* S3PutObjectAction: */
  S3_ADDB_S3_PUT_OBJECT_ACTION_ID,
  /* S3PutObjectTaggingAction: */
  S3_ADDB_S3_PUT_OBJECT_TAGGING_ACTION_ID,

  /* End of auto-generated IDs. */
  S3_ADDB_LAST_REQUEST_ID = S3_ADDB_S3_PUT_OBJECT_TAGGING_ACTION_ID,

  /* End of S3 server range. */
  S3_ADDB_RANGE_END = S3_ADDB_LAST_REQUEST_ID
};

#endif
