#!/usr/bin/env bash
set -e

#
# Wrapper script for Jenkins test '03initscript-tests'
#

M0_SRC_DIR=`readlink -f $0`
M0_SRC_DIR=${M0_SRC_DIR%/*/*}

. $M0_SRC_DIR/utils/functions # report_and_exit

cd $M0_SRC_DIR

sudo ./scripts/install-mero-service -u
sudo ./scripts/install-mero-service -l
sudo /usr/bin/time -v ./st/m0t1fs -vv

report_and_exit initscripts $?
