#!/usr/bin/env bash

SANDBOX_DIR=${SANDBOX_DIR:-/var/mero/sandbox.m0confgen}
M0_SRC_DIR=`readlink -f $0`
M0_SRC_DIR=${M0_SRC_DIR%/*/*}

. $M0_SRC_DIR/utils/functions # report_and_exit

(
    set -eu -o pipefail

    OUTPUT_FORMATS='confgen xcode json html dot'
    CG_FILE=$M0_SRC_DIR/ut/conf.cg

    m0confgen() { $M0_SRC_DIR/utils/m0confgen "$@"; }

    m0confgen --self-check
    m0confgen $CG_FILE | m0confgen -f xcode -t confgen >/dev/null
    for to_fmt in $OUTPUT_FORMATS; do
        m0confgen -f confgen -t $to_fmt $CG_FILE >/dev/null
    done
)
rc=$?

if [[ $rc -eq 0 && -d $SANDBOX_DIR ]]; then
    rm -r $SANDBOX_DIR
fi

report_and_exit m0confgen $rc
