
clovis_m0clovis_m0clovis_SOURCES = clovis/m0clovis/clovis_cmd_main.c \
		      clovis/m0clovis/clovis_index.c \
		      clovis/m0clovis/clovis_index_parser.c \
		      clovis/m0clovis/clovis_index_op.c \
		      clovis/m0clovis/clovis_index.h \
		      clovis/m0clovis/clovis_index_parser.h \
		      clovis/m0clovis/clovis_index_op.h \
		      clovis/m0clovis/clovis_common.h

EXTRA_DIST  += clovis/st/utils/m0clovis_st.sh \
	       clovis/st/utils/m0clovis_start.sh

