/* -*- C -*- */
/*
 * COPYRIGHT 2013 XYRATEX TECHNOLOGY LIMITED
 *
 * THIS DRAWING/DOCUMENT, ITS SPECIFICATIONS, AND THE DATA CONTAINED
 * HEREIN, ARE THE EXCLUSIVE PROPERTY OF XYRATEX TECHNOLOGY
 * LIMITED, ISSUED IN STRICT CONFIDENCE AND SHALL NOT, WITHOUT
 * THE PRIOR WRITTEN PERMISSION OF XYRATEX TECHNOLOGY LIMITED,
 * BE REPRODUCED, COPIED, OR DISCLOSED TO A THIRD PARTY, OR
 * USED FOR ANY PURPOSE WHATSOEVER, OR STORED IN A RETRIEVAL SYSTEM
 * EXCEPT AS ALLOWED BY THE TERMS OF XYRATEX LICENSES AND AGREEMENTS.
 *
 * YOU SHOULD HAVE RECEIVED A COPY OF XYRATEX'S LICENSE ALONG WITH
 * THIS RELEASE. IF NOT PLEASE CONTACT A XYRATEX REPRESENTATIVE
 * http://www.xyratex.com/contact
 *
 * Original author: Anand Vidwansa <anand_vidwansa@xyratex.com>
 * Original creation date: 12/17/2012
 */

#pragma once

#ifndef __MERO_LIB_VIRTUAL_ARRAY_PRIVATE_H__
#define __MERO_LIB_VIRTUAL_ARRAY_PRIVATE_H__

M0_EXTERN void *m0_varr_buf_alloc(size_t bufsize);
M0_EXTERN void  m0_varr_buf_free(void *buf, size_t bufsize);

struct varr_cache {
	unsigned long *vc_buff;
	uint64_t       vc_first_index;
	uint64_t       vc_last_index;
};

#endif /* __MERO_LIB_VIRTUAL_ARRAY_PRIVATE_H__ */
