@startuml

' Can be previewed in VS Code or other editors.
' References:
' 1: https://drive.google.com/open?id=1KngBz2HGdbCv-pmjeu6df_gYxfC3YUtHpWY4CNuZ6NU
' 2: https://drive.google.com/open?id=1-VkNcDdA0KYwY4WpArMs-ChdI7u_vhd7-7Dp5TqQ-BA
' 3: https://drive.google.com/open?id=1JQnJnZafl_kzSOocMI-G-jNzXGjJQFfRAS9O6R-IizI
' 4: https://drive.google.com/open?id=1GjLfZ9VRdkE3UnFCx-jknPFTpFlzY5KNtgB1ujwq-to

header S3 Metadata structure\n By Kaustubh Deorukhkar\n2019-12-02
title S3 Metadata

center footer Index Classes here represent EOS-Core (mero) KVS Index, a list of Key-Value pairs

package "Global Root Indexes" #DDDDDD {
    class GlobalBucketListIndex
    class GlobalAccountBucketListIndex
    class GlobalS3ServiceInstanceListIndex
    class GlobalProbableDeleteListIndex
}

package "First Level Indexes" #DDDDDE {
    class ObjectListIndex
    class ObjectVersionsListIndex
}

package "Multipart upload Indexes" #DDDDDF {
    class MultipartListIndexPerBucket
    class PartinfoList
}

' Root index created on initial S3 startup.
class GlobalS3ServiceInstanceListIndex {
    service_list : List<S3ServiceInstanceEntry>
}

class S3ServiceInstanceEntry {
    process_fid : ClovisProcessFid
    ' Lifecycle counter: Created on service startup or
    ' refresh service on unrecoverable failures - equal to fresh start
    instance_uuid : UUID
}

' Root index created on initial S3 startup.
class GlobalProbableDeleteListIndex {
    probable_delete_list : List<ProbableDeleteEntry>
}

class ProbableDeleteEntry {
    object_oid : OID
    delete_metadata : ProbableDeleteEntryMetadata
}

class ProbableDeleteEntryMetadata {
    object_name : String
    object_list_index_id : OID
    layout_id : Integer
    ' Service instance id of s3 process that created this entry.
    service_instance_id : UUID
}
note bottom of ProbableDeleteEntryMetadata
    * Serialized as JSON
    * Helps indentify if object may be accessed which can be verified
      by looking up GlobalS3ServiceInstanceListIndex
end note

' Root index created on initial S3 startup.
class GlobalBucketListIndex {
    bucket_acc_list : List<BucketAccountEntry>
}

class BucketAccountEntry {
    ' Sample BucketForEOSGroup
    bucket_name : String
    bucket_account_mapping : BucketAccountMapping
}

note bottom of BucketAccountMapping : Serialized as JSON
class BucketAccountMapping {
    account_id : String
    region : String
}


' Bucket metadata Json
note bottom of BucketMetadata : Serialized as JSON
class BucketMetadata {
    object_list_index_oid: OID
    multipart_list_per_bucket_index_oid: OID
    more_metadata : String
    ' ... more metadata attributes, acl, polciy etc
}

' Root index created on initial S3 startup.
class GlobalAccountBucketListIndex {
    ' A1/B1 type keys for bucket listing in an account
    bucket_list : List<AccountBucketEntry>
}

class AccountBucketEntry {
    ' Sample A1/B1 or SeagateAccount/BucketForEOSGroup
    account_slash_bucket_name : String
    bucket_metadata : BucketMetadata
}

class ObjectListIndex {
    object_list: List<ObjectEntry>
}

' Key-value pair for an object storing objects metadata json as value and key being objectname
class ObjectEntry {
    ' Sample Obj1 or pune.jpg
    object_name : String
    object_metadata : ObjectMetadata
}

' Object metadata Json
note bottom of ObjectMetadata : Serialized as JSON
class ObjectMetadata {
    object_version_list_index_oid: OID
    more_metadata : String
    ' ... more metadata attributes, size, md5, acl etc
}

class ObjectVersionsListIndex {
    object_list : List<ObjectVersionEntry>
}

class ObjectVersionEntry {
    ' Sample v1 or v1asdf123
    object_version_id : String
    object_metadata : ObjectMetadata
}

' Index created for each bucket and has listing of each multipart upload in-progress
class MultipartListIndexPerBucket {
    multipart_upload_list : List<MultiPartMetadataEntry>
}

class MultiPartMetadataEntry {
    object_name : String
    multipart_metadata : MultiPartMetadata
}

note bottom of MultiPartMetadata : Serialized as JSON. Eventually this converts in ObjectMetadata
class MultiPartMetadata {
    upload_id : UUID
    part_info_list_index_oid: OID
    more_metadata : String
    ' ... more metadata attributes, size, md5, acl etc
}

class PartinfoList {
    part_number: String
    part_metadata: PartMetadata
}

class PartMetadata {
    ' Contains information for a part uploaded.
    part_number : String
    more_metadata : String
    ' ... more metadata attributes
}

' Relationships

GlobalS3ServiceInstanceListIndex "0" *-- "many" S3ServiceInstanceEntry : contains
GlobalBucketListIndex "0" *-- "many" BucketAccountEntry : contains
BucketAccountEntry "1" *-- "1" BucketAccountMapping : contains

GlobalAccountBucketListIndex "0" *-- "many" AccountBucketEntry : contains
AccountBucketEntry "1" *-- "1" BucketMetadata : contains

GlobalProbableDeleteListIndex "0" *-- "many" ProbableDeleteEntry : contains
ProbableDeleteEntry "1" *-- "1" ProbableDeleteEntryMetadata : contains

ObjectListIndex "0" *-- "many" ObjectEntry : contains
ObjectEntry "1" *-- "1" ObjectMetadata : contains

ObjectVersionsListIndex "0" *-- "many" ObjectVersionEntry : contains
ObjectVersionEntry "1" *-- "1" ObjectMetadata : contains

MultipartListIndexPerBucket "0" *-- "many" MultiPartMetadataEntry : contains
MultiPartMetadataEntry "1" *-- "1" MultiPartMetadata
PartinfoList "0" *-- "many" PartMetadata : contains

@enduml