FROM centos:7.8.2003
CMD ["/bin/bash"]
# RUN yum install -y python3
# RUN yum repolist
# RUN yum -y --enablerepo=extras install epel-release
# RUN yum install -y python-pip
# RUN pip install pip==20.3.3
# RUN yum install -y ansible
# RUN yum install -y gcc rpm-build python36 python36-pip python36-devel python36-setuptools openssl-devel libffi-devel
# RUN yum install -y git 
# RUN pip3 install wheel
# RUN git clone --recursive https://github.com/Seagate/cortx-utils -b main && cd ./cortx-utils/py-utils && python3 setup.py bdist_wheel && cd .. && ./jenkins/build.sh -v 2.0.0 -b 2 && cd ./py-utils/dist && pip3 install cortx_py_utils-1.0.0-py3-none-any.whl
