nobase_mero_include_HEADERS += fis/fi_command.h \
                               fis/fi_command_fom.h \
                               fis/fi_command_fops.h \
                               fis/fi_service.h

mero_libmero_la_SOURCES += fis/fi_command.c \
                           fis/fi_command_fom.c \
                           fis/fi_command_fops.c \
                           fis/fi_service.c

nodist_mero_libmero_la_SOURCES += fis/fi_command_xc.c

XC_FILES += fis/fi_command_xc.h
