#!/bin/sh -e
# S3 server stop script in deployment environment.
#   Usage: s3stopsystem.sh <process FID>
#             where process FID: S3 server process FID generated by halon.

if [ $# -ne 1 ]; then
  echo "Invalid number of arguments passed to the script"
  echo "Usage: s3stopsystem.sh <process FID>"
  exit 1
fi

pidfile='/var/run/s3server.'$1'.pid'

if [[ -r $pidfile ]]; then
  pidstr=`cat $pidfile`
  if [ "$pidstr" != "" ]; then
    kill -s TERM $pidstr
    if [ "$?" != "0" ]; then
      rm $pidfile
    fi
  fi
fi
