#!/usr/bin/env bash
set -eu

SANDBOX_DIR=${SANDBOX_DIR:-/var/mero/sandbox.ham-st}

M0_SRC_DIR="$(readlink -f $0)"
M0_SRC_DIR="${M0_SRC_DIR%/*/*/*}"
[ -n "${SUDO:-}" ] || SUDO='sudo -E'

. "$M0_SRC_DIR/utils/functions" # sandbox_init, report_and_exit

sandbox_init
$SUDO "$M0_SRC_DIR/conf/st" insmod
rc=0; "$M0_SRC_DIR/ha/ham-st" || rc=$?
$SUDO "$M0_SRC_DIR/conf/st" rmmod
sandbox_fini $rc
report_and_exit ham $rc
