#= <6400000000000001:4a>: dev_idx (10) does not belong [0, P) range; P=10
(root-0 verno=1 rootfid=(0xb, 0x16) mdpool=pool-4 imeta_pver=pver-8
    mdredundancy=2 params=["param-0", "param-1", "param-2"]
    nodes=[node-2, node-48] sites=[site-2] pools=[pool-4, pool-56]
    profiles=[profile-0] fdmi_flt_grps=[])
(profile-0 pools=[pool-4, pool-56])
(node-2 memsize=16000 nr_cpu=2 last_state=3 flags=2
    processes=[process-5, process-6])
(process-5 cores=[3] mem_limit_as=0 mem_limit_rss=0 mem_limit_stack=0
    mem_limit_memlock=0 endpoint="0@lo:12345:34:1"
    services=[service-9, service-10, service-20, service-21,
              service-22, service-23, service-24, service-25, service-26])
(process-6 cores=[3] mem_limit_as=0 mem_limit_rss=0 mem_limit_stack=0
    mem_limit_memlock=0 endpoint="0@lo:12345:34:1" services=[])
(service-9 type=@M0_CST_IOS endpoints=["0@lo:12345:34:1"] params=[]
    sdevs=[sdev-15, sdev-71, sdev-72, sdev-73, sdev-74])
(service-10 type=@M0_CST_MDS endpoints=["0@lo:12345:34:1"] params=[] sdevs=[])
(service-20 type=@M0_CST_CONFD endpoints=["0@lo:12345:34:1"] params=[] sdevs=[])
(service-21 type=@M0_CST_ADDB2 endpoints=["0@lo:12345:34:1"] params=[] sdevs=[])
(service-22 type=@M0_CST_RMS endpoints=["0@lo:12345:34:1"] params=[] sdevs=[])
(service-23 type=@M0_CST_HA endpoints=["0@lo:12345:34:1"] params=[] sdevs=[])
(service-24 type=@M0_CST_SNS_REP endpoints=["0@lo:12345:34:1"] params=[]
    sdevs=[])
(service-25 type=@M0_CST_SNS_REB endpoints=["0@lo:12345:34:1"] params=[]
    sdevs=[])
(service-26 type=@M0_CST_DS1 endpoints=["0@lo:12345:34:1"] params=[] sdevs=[])
(sdev-15 dev_idx=0 iface=7 media=2 bsize=8192 size=1073741824 last_state=2
    flags=4 filename="/dev/sdev1")
(sdev-71 dev_idx=2 iface=7 media=2 bsize=8192 size=1073741824 last_state=2
    flags=4 filename="/dev/sdev3")
(sdev-72 dev_idx=3 iface=7 media=2 bsize=8192 size=1073741824 last_state=2
    flags=4 filename="/dev/sdev4")
(sdev-73 dev_idx=4 iface=7 media=2 bsize=8192 size=1073741824 last_state=2
    flags=4 filename="/dev/sdev5")
(sdev-74
    dev_idx=10 # does not belong [0, P) range; P=10
    iface=7 media=2 bsize=8192 size=1073741824 last_state=2 flags=4
    filename="/dev/sdev6")
(site-2 racks=[rack-3, rack-52] pvers=[pver-8, pver-57])
(rack-3 encls=[enclosure-7] pvers=[pver-8])
(enclosure-7 ctrls=[controller-11] pvers=[pver-8])
(controller-11 node=node-2
    drives=[drive-16, drive-75, drive-76, drive-77, drive-78]
    pvers=[pver-8])
(drive-16 dev=sdev-15 pvers=[pver-8])
(drive-75 dev=sdev-71 pvers=[pver-8])
(drive-76 dev=sdev-72 pvers=[pver-8])
(drive-77 dev=sdev-73 pvers=[pver-8])
(drive-78 dev=sdev-74 pvers=[pver-8])
(pool-4 pver_policy=0 pvers=[pver-8])
(pver-8 N=3 K=1 P=5 tolerance=[0, 0, 0, 0, 1] sitevs=[objv-2:12])
(objv-2:12 real=site-2 children=[objv-12])
(objv-12 real=rack-3 children=[objv-17])
(objv-17 real=enclosure-7 children=[objv-18])
(objv-18 real=controller-11
    children=[objv-19, objv-79, objv-80, objv-81, objv-82])
(objv-19 real=drive-16 children=[])
(objv-79 real=drive-75 children=[])
(objv-80 real=drive-76 children=[])
(objv-81 real=drive-77 children=[])
(objv-82 real=drive-78 children=[])
(node-48 memsize=16000 nr_cpu=2 last_state=3 flags=2 processes=[process-49])
(process-49 cores=[3] mem_limit_as=0 mem_limit_rss=0 mem_limit_stack=0
    mem_limit_memlock=0 endpoint="0@lo:12345:34:1"
    services=[service-27, service-28])
(service-27 type=@M0_CST_IOS endpoints=["0@lo:12345:34:1"] params=[]
    sdevs=[sdev-51, sdev-83, sdev-84, sdev-85, sdev-86])
(service-28 type=@M0_CST_DS2 endpoints=["0@lo:12345:34:1"] params=[] sdevs=[])
(sdev-51 dev_idx=1 iface=4 media=1 bsize=4096 size=1073741824 last_state=3
    flags=4 filename="/dev/sdev2")
(sdev-83 dev_idx=6 iface=4 media=1 bsize=4096 size=1073741824 last_state=3
    flags=4 filename="/dev/sdev7")
(sdev-84 dev_idx=7 iface=4 media=1 bsize=4096 size=1073741824 last_state=3
    flags=4 filename="/dev/sdev8")
(sdev-85 dev_idx=8 iface=4 media=1 bsize=4096 size=1073741824 last_state=3
    flags=4 filename="/dev/sdev9")
(sdev-86 dev_idx=9 iface=4 media=1 bsize=4096 size=1073741824 last_state=3
    flags=4 filename="/dev/sdev10")
(rack-52 encls=[enclosure-53] pvers=[pver-57])
(enclosure-53 ctrls=[controller-54] pvers=[pver-57])
(controller-54 node=node-48
    drives=[drive-55, drive-87, drive-88, drive-89, drive-90]
    pvers=[pver-57])
(drive-55 dev=sdev-51 pvers=[pver-57])
(drive-87 dev=sdev-83 pvers=[pver-57])
(drive-88 dev=sdev-84 pvers=[pver-57])
(drive-89 dev=sdev-85 pvers=[pver-57])
(drive-90 dev=sdev-86 pvers=[pver-57])
(pool-56 pver_policy=0 pvers=[pver-57])
(pver-57 N=3 K=1 P=5 tolerance=[0, 0, 0, 0, 1] sitevs=[objv-2:58])
(objv-2:58 real=site-2 children=[objv-58])
(objv-58 real=rack-52 children=[objv-59])
(objv-59 real=enclosure-53 children=[objv-60])
(objv-60 real=controller-54
    children=[objv-61, objv-91, objv-92, objv-93, objv-94])
(objv-61 real=drive-55 children=[])
(objv-91 real=drive-87 children=[])
(objv-92 real=drive-88 children=[])
(objv-93 real=drive-89 children=[])
(objv-94 real=drive-90 children=[])
