nobase_mero_include_HEADERS += rm/rm.h \
			       rm/rm_fops.h \
			       rm/rm_foms.h \
			       rm/rm_service.h \
			       rm/rm_rwlock.h \
			       rm/rm_ha.h \
			       rm/rm_internal.h

mero_libmero_la_SOURCES     += rm/rm_fops.c \
			       rm/rm.c \
			       rm/rm_foms.c \
			       rm/rm_service.c \
			       rm/rm_rwlock.c \
			       rm/rm_ha.c

nodist_mero_libmero_la_SOURCES  += rm/rm_fops_xc.c

XC_FILES                    += rm/rm_fops_xc.h
