#!/usr/bin/env bash

# exit immediately if one the commands exits with a non-zero status
set -e

# global variables, which can be overriden in /etc/sysconfig/mero
MERO_GENDERS_CONF=/etc/mero/genders

# service local variables
user_config=/etc/sysconfig/mero
kernel_config=/etc/sysconfig/mero-kernel
service_funcs=/usr/libexec/mero/mero-service.functions


start()
{
    source $service_funcs

    [[ -r $kernel_config ]] && source $kernel_config
    [[ -r $user_config   ]] && source $user_config

    m0_load_modules
}

stop()
{
    source $service_funcs

    [ -r $user_config ] && source $user_config

    m0_unload_modules
}


case $1 in
    start)  start ;;
    stop)   stop ;;
esac
