#!/usr/bin/env bash

# exit immediately if one the commands exits with a non-zero status
set -e

# constants
readonly PROG_NAME=$(basename $0)

# global variables, which can be overriden in /etc/sysconfig/mero
MERO_GENDERS_CONF=/etc/mero/genders

# service local variables
user_config=/etc/sysconfig/mero
service_funcs=/usr/libexec/mero/mero-service.functions

calc_log_rotation_options()
{
    local free_space_mb=$(df -BM $MERO_LOG_DIR | tail -n1 | awk '{print $4}' | sed -e 's/M$//')
    local trace_targets=$(( $(m0_get_services | wc -w) + 1)) # +1 is for mero-kernel
    local log_space_per_service=$(( free_space_mb / trace_targets ))
    local min_log_space_per_service=$(( MERO_TRACED_MIN_LOG_CHUNK_SIZE_MB * MERO_TRACED_MIN_LOG_CHUNKS ))
    local max_log_space_per_service=$(( MERO_TRACED_MAX_LOG_CHUNK_SIZE_MB * MERO_TRACED_MAX_LOG_CHUNKS ))

    if (( $log_space_per_service < $min_log_space_per_service )) ; then
        m0_exit "not enough free space available on '$MERO_LOG_DIR' for trace logs," \
                "required: $min_log_space_per_service MB per service," \
                "available: $log_space_per_service MB per service"
    fi

    local space=$max_log_space_per_service
    local ratio=1
    while (( $space > $log_space_per_service )) ; do
        space=$(( space / 4 ))
        (( ratio++ ))
    done

    local chunk_size_mb=$(( MERO_TRACED_MAX_LOG_CHUNK_SIZE_MB / ratio ))
    local chunks_num=$(( MERO_TRACED_MAX_LOG_CHUNKS / ratio ))

    if (( $chunk_size_mb > $MERO_TRACED_MAX_LOG_CHUNK_SIZE_MB )) ; then
        chunk_size_mb=$MERO_TRACED_MIN_LOG_CHUNK_SIZE_MB
    fi

    if (( $chunks_num > $MERO_TRACED_MAX_LOG_CHUNKS )) ; then
        chunks_num=$MERO_TRACED_MIN_LOG_CHUNKS
    fi

    m0_log "mero-trace: rotation scheme: ${chunk_size_mb}MB/x$chunks_num"

    echo "-s $chunk_size_mb -k $chunks_num"
}

cleanup_old_logs()
{
    local service=$1

    cd $MERO_LOG_DIR

    case "$service" in
        kernel)
            local img_mask='m0mero.ko~*.img'
            local log_mask='trace-m0mero~*.bin'
            ;;

        confd*|ha*|ios*|cas*|mds*|rms*|fdmi*)
            local log_mask='trace-m0d-'$service'-*.bin'
            ;;

        m0d-*)
            local log_mask='trace-m0d-'${service#m0d-}'-*.bin'
            ;;
    esac

    m0_log 'cleaning up old logs'
    set +e
    for mask in img_mask log_mask ; do
        if [[ -n ${!mask} ]] ; then
            ls -t -1 ${!mask} \
            | tail -n +$(( $MERO_TRACED_KEEP_LOGS_NUM + 1 )) \
            | sed -e 's/$/*/' \
            | xargs bash -c 'rm -vf $@' argv0_placeholder
        fi
    done
    set -e

    cd -
}

m0_traced()
{
    local target=$1

    [[ -n $target ]] || m0_exit "usage: $PROG_NAME <SERVICE>"

    source $service_funcs

    [ -r $user_config ] && source $user_config

    [ ! -d "$MERO_LOG_DIR" ] && mkdir -p "$MERO_LOG_DIR"

    local date=$(date -u '+%F_%T')
    local m0traced=$(m0_path_to m0traced)

    case "$target" in
        kernel)
            [[ $MERO_TRACED_KMOD == yes ]] || exit 0
            local m0mero_ko_img=$MERO_LOG_DIR/m0mero.ko~$date.img
            local output_file=$MERO_LOG_DIR/trace-m0mero~$date.bin
            local opts="-K -O $m0mero_ko_img"
            ln -sf $(basename $m0mero_ko_img) /var/log/mero/m0mero_ko.img
            if ! mount | grep -q /sys/kernel/debug ; then
                mount -t debugfs none /sys/kernel/debug
            fi
            ;;

        confd*|ha*|ios*|cas*|mds*|rms*|fdmi*)
            [[ $MERO_TRACED_M0D == yes ]] || exit 0
            local server_pid=$(m0_get_server_pid_for $target)
            local trace_file_dir=$(m0_get_m0d_data_dir_for $target)
            [[ -z $MERO_M0D_TRACE_DIR ]] || trace_file_dir=$MERO_M0D_TRACE_DIR/$target
            local server_trace_file=$trace_file_dir/m0trace.$server_pid
            local opts="-S -i $server_trace_file ${MERO_TRACED_CHECK_INPUT:+-m $MERO_TRACED_CHECK_INPUT}"
            local output_file=$MERO_LOG_DIR/trace-m0d-$target-$server_pid~$date.bin
            ;;

        m0d-*)
            [[ $MERO_TRACED_M0D == yes ]] || exit 0
            local server_pid=$(m0_get_server_pid_for $target)
            local trace_file_dir=$(m0_get_m0d_data_dir_for $target)
            [[ -z $MERO_M0D_TRACE_DIR ]] || trace_file_dir=$MERO_M0D_TRACE_DIR/$target
            local server_trace_file=$trace_file_dir/m0trace.$server_pid
            local opts="-S -i $server_trace_file ${MERO_TRACED_CHECK_INPUT:+-m $MERO_TRACED_CHECK_INPUT}"
            local output_file="$MERO_LOG_DIR/trace-m0d-${target#m0d-}-$server_pid~$date.bin"
            ;;

        *) m0_exit "Failed to start m0traced for unknown target '$target'," \
                   "available targets are 'kernel', 'confd*', 'ios*', 'cas*', 'fdmi*'" \
                   "'mds*' and 'ha*'"
            ;;
    esac

    cleanup_old_logs $target

    local log_rotation_opts=$(calc_log_rotation_options)
    [[ -n $log_rotation_opts ]] ||
        exit 1

    set -x
    exec $m0traced -L $opts $log_rotation_opts -o "$output_file" $MERO_TRACED_EXTRA_OPTS
}


m0_traced $(echo $1 | sed -r -e 's/^mero-(server[-@])?//' \
                             -e 's/^(0x)?[0-9a-f]+:(0x)?[0-9a-f]+$/m0d-&/')
