version: '3'

services:
  app:
    container_name: mydrive-node-no-mongo
    restart: always
    build: .
    ports: 
      - '3000:3000'
      - '8080:8080'
    env_file:
      - docker-variables.env
 