/*
 * COPYRIGHT 2017 SEAGATE LLC
 *
 * THIS DRAWING/DOCUMENT, ITS SPECIFICATIONS, AND THE DATA CONTAINED
 * HEREIN, ARE THE EXCLUSIVE PROPERTY OF SEAGATE TECHNOLOGY
 * LIMITED, ISSUED IN STRICT CONFIDENCE AND SHALL NOT, WITHOUT
 * THE PRIOR WRITTEN PERMISSION OF SEAGATE TECHNOLOGY LIMITED,
 * BE REPRODUCED, COPIED, OR DISCLOSED TO A THIRD PARTY, OR
 * USED FOR ANY PURPOSE WHATSOEVER, OR STORED IN A RETRIEVAL SYSTEM
 * EXCEPT AS ALLOWED BY THE TERMS OF SEAGATE LICENSES AND AGREEMENTS.
 *
 * YOU SHOULD HAVE RECEIVED A COPY OF SEAGATE'S LICENSE ALONG WITH
 * THIS RELEASE. IF NOT PLEASE CONTACT A SEAGATE REPRESENTATIVE
 * http://www.seagate.com/contact
 *
 * Original author:  Kaustubh Deorukhkar   <kaustubh.deorukhkar@seagate.com>
 * Original creation date: 27-Mar-2017
 */

#pragma once

#ifndef __S3_UT_S3_TEST_UTILS_H__
#define __S3_UT_S3_TEST_UTILS_H__

#include <gmock/gmock.h>
#include <gtest/gtest.h>

#define EXPECT_OID_EQ(O1, O2)  \
  EXPECT_EQ(O1.u_lo, O2.u_lo); \
  EXPECT_EQ(O1.u_hi, O2.u_hi);

#define EXPECT_OID_NE(O1, O2)  \
  EXPECT_NE(O1.u_lo, O2.u_lo); \
  EXPECT_NE(O1.u_hi, O2.u_hi);

#endif
