net_test_libmero_net_test_la_SOURCES += net/test/commands.c \
					net/test/console.c \
					net/test/initfini.c \
					net/test/network.c \
					net/test/node.c \
					net/test/node_bulk.c \
					net/test/node_helper.c \
					net/test/node_ping.c \
					net/test/node_stub.c \
					net/test/ringbuf.c \
					net/test/serialize.c \
					net/test/service.c \
					net/test/slist.c \
					net/test/stats.c \
					net/test/str.c \
					net/test/commands.h \
					net/test/console.h \
					net/test/debug.h \
					net/test/initfini.h \
					net/test/network.h \
					net/test/node.h \
					net/test/node_bulk.h \
					net/test/node_helper.h \
					net/test/node_ping.h \
					net/test/node_stub.h \
					net/test/ringbuf.h \
					net/test/serialize.h \
					net/test/service.h \
					net/test/slist.h \
					net/test/stats.h \
					net/test/str.h \
					net/test/user_space/stats_u.c \
					net/test/user_space/stats_u.h

EXTRA_DIST += net/test/test-user.sh.in \
              net/test/linux_kernel/node_k.c \
              net/test/run.sh \
              net/test/test.sh
