/* -*- C -*- */
/*
 * COPYRIGHT 2019 XYRATEX TECHNOLOGY LIMITED
 *
 * THIS DRAWING/DOCUMENT, ITS SPECIFICATIONS, AND THE DATA CONTAINED
 * HEREIN, ARE THE EXCLUSIVE PROPERTY OF XYRATEX TECHNOLOGY
 * LIMITED, ISSUED IN STRICT CONFIDENCE AND SHALL NOT, WITHOUT
 * THE PRIOR WRITTEN PERMISSION OF XYRATEX TECHNOLOGY LIMITED,
 * BE REPRODUCED, COPIED, OR DISCLOSED TO A THIRD PARTY, OR
 * USED FOR ANY PURPOSE WHATSOEVER, OR STORED IN A RETRIEVAL SYSTEM
 * EXCEPT AS ALLOWED BY THE TERMS OF XYRATEX LICENSES AND AGREEMENTS.
 *
 * YOU SHOULD HAVE RECEIVED A COPY OF XYRATEX'S LICENSE ALONG WITH
 * THIS RELEASE. IF NOT PLEASE CONTACT A XYRATEX REPRESENTATIVE
 * http://www.xyratex.com/contact
 *
 * Original author: Anatoliy Bilenko <anatoliy.bilenko@seagate.com>
 * Original creation date: 28-Aug-2019
 */

#pragma once

#ifndef __MERO_DIX_DIX_ADDB_H__
#define __MERO_DIX_DIX_ADDB_H__

/**
 * @defgroup DIX
 *
 * @{
 */

#include "addb2/identifier.h"  /* M0_AVI_DIX_RANGE_START */
#include "xcode/xcode_attr.h"

enum m0_avi_dix_labels {
	M0_AVI_DIX_SM_REQ = M0_AVI_DIX_RANGE_START + 1,
	M0_AVI_DIX_SM_REQ_COUNTER,
	M0_AVI_DIX_SM_REQ_COUNTER_END = M0_AVI_DIX_SM_REQ_COUNTER + 0x100,

	M0_AVI_DIX_TO_MDIX,
	M0_AVI_DIX_TO_CAS,

	M0_AVI_DIX_REQ_ATTR_IS_META,
	M0_AVI_DIX_REQ_ATTR_REQ_TYPE,
	M0_AVI_DIX_REQ_ATTR_ITEMS_NR,
	M0_AVI_DIX_REQ_ATTR_INDICES_NR,
	M0_AVI_DIX_REQ_ATTR_KEYS_NR,
	M0_AVI_DIX_REQ_ATTR_VALS_NR,
} M0_XCA_ENUM;


/** @} end of DIX group */
#endif /* __MERO_DIX_DIX_ADDB_H__ */

/*
 *  Local variables:
 *  c-indentation-style: "K&R"
 *  c-basic-offset: 8
 *  tab-width: 8
 *  fill-column: 80
 *  scroll-step: 1
 *  End:
 */
/*
 * vim: tabstop=8 shiftwidth=8 noexpandtab textwidth=80 nowrap
 */
