#!/usr/bin/env bash

#
# Main script for mero-build Jenkins job
#

# auto export all variables
set -a

# exit with error code on any command failure (including pipes)
set -e
set -o pipefail


WORKSPASE=$(pwd)
ARTIFACTS=$WORKSPASE/artifacts

# for backward compatibility with old Jenkins environment we need to `cd` into
# 'workdir/src' directory if it exists, that is where old Jenkins jobs stored
# mero sources
src_dir=workdir/src
[[ ! -d $src_dir ]] || cd $src_dir

sudo git clean -dfx
sudo git submodule foreach git clean -dfx
git submodule update

if [[ -d $ARTIFACTS ]] ; then
    rm -f $ARTIFACTS/*
else
    mkdir $ARTIFACTS
fi

./autogen.sh |& tee $ARTIFACTS/configure.log

if [[ $1 = docs ]] ; then
./configure --disable-systemd |& tee -a $ARTIFACTS/configure.log
make -j doc |& tee $ARTIFACTS/make.log
else
[[ -d $HOME/rpmbuild ]] && rm -rf $HOME/rpmbuild/*
./configure |& tee -a $ARTIFACTS/configure.log
make -j |& tee $ARTIFACTS/make.log
cp -v xcode/protocol*.txt $ARTIFACTS/
make -j rpms |& tee $ARTIFACTS/rpm.log
cp -av $HOME/rpmbuild/RPMS/x86_64/*.rpm $ARTIFACTS/
cp -av $HOME/rpmbuild/SRPMS/*.rpm $ARTIFACTS/
(cd $ARTIFACTS/ ; ln -vs eos-core-[[:digit:]]*.x86_64.rpm mero-latest.rpm)
fi
