#!/usr/bin/env bash
set -eu

FILTER='tail -3'
INTERACTIVE=0
COLOR_1='\033[33m'          # fg=yellow
COLOR_2='\033[30m\033[47m'  # fg=black, bg=white
NO_COLOR='\033[0m'

die() { echo "$@" >&2; exit 1; }

url_dir() {
	echo -n "http://jenkins-fre.xyus.xyratex.com:8080/job/"
	echo "mero-test-gerrit/${1}/artifact/workdir/mero-single"
}

inter() { if [ $INTERACTIVE -eq 1 ]; then "$@"; fi; }

say() {
	inter echo -en "$COLOR_1"
	echo "$@"
	inter echo -en "$NO_COLOR"
}

usage() {
	cat <<EOF
Usage: ${0##*/} [OPTION]... <mero-test-gerrit #>...

Options:
    -i, --interactive    Pause after each test #.
    --full               Show full output (\`$FILTER' is used by default).
    -h, --help           Show this help and exit.
EOF
}

### ----------------------------------------------------------------------
### main
### ----------------------------------------------------------------------

while [ $# -gt 0 -a "${1#-}" != "$1" ]; do  # for each arg that starts with `-'
	case "$1" in
		-h|--help)        usage; exit 0;;
		-i|--interactive) INTERACTIVE=1; shift;;
		--full)           FILTER=cat; shift;;
		*) echo "Unknown option: $1" >&2; die "`usage`";;
	esac
done
[ $# -gt 0 ] || die "`usage`"

inter trap "echo -en '$NO_COLOR'" 0
for test_id in "$@"; do
	inter clear
	say "* $(url_dir $test_id)/"
	for f in 0{0userspace,1kernel,2system}-tests.\
{stdout,stderr,messages.colibri}.log; do
		say "** $f"
		wget -qO- "$(url_dir $test_id)/$f" | $FILTER
	done
	inter echo -en "$COLOR_2"
	inter read -p 'Press Enter to continue... '
	inter echo -en "$NO_COLOR"
done
