#!/usr/bin/env bash

#
# Decode addresses from dynamic libraries loaded into running m0d.
#

for w in $*
do
    for p in $(pgrep m0d)
    do
	gdb -ex "x 0x$w" --batch /proc/$p/exe $p 2>/dev/null
    done | grep "^0x$w .*:"
done
