#!/usr/bin/env bash

pid=$1
image=$2

for kt in /proc/$pid/task/* ;do
    echo "Kernel stack for $kt"
    cat $kt/stack
done

echo "User stacks for $pid"
/usr/bin/gdb -batch -n -ex "thread apply all bt" $image $pid

