m0ut_objects += ut/cs_fop.o \
                ut/cs_fop_xc.o \
                ut/cs_service.o \
                ut/misc.o \
                ut/module.o \
                ut/be.o \
                ut/threads.o \
                ut/ut.o \
		ut/stob.o \
                ut/linux_kernel/ut.o \
                ut/ut_rpc_machine.o \
